# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :lint do
    swiftlint()
  end

  desc "Builds the project w/o archiving"
  lane :build do
    gym(
      project: "SwiftUIKit.xcodeproj",
      include_symbols: true,
      scheme: "SwiftUIKit",
      skip_archive: true,
      skip_codesigning: true,
      silent: false,
      clean: false
    )
  end

  lane :test do
    scan(
      project: "SwiftUIKit.xcodeproj",
      devices: ["iPhone 12"],
      scheme: "SwiftUIKit",
      clean: false
    )
  end
end
